### PR TITLE
Minor bugfix where French was displayed as "France"

### PR DESCRIPTION
**Pull request by Sankie005**
Really minor issue but French was displayed as "France" in the UI, this pr should fix it :D

### CODE REVIEW

**Comment by xBoyMinemc** [comment]
so?  

    The French Republic,La République française

so,do i?
  https://github.com/codenoid/github-roast/pull/42

**Comment by Sankie005** [comment]
> so?
> 
> ```
> The French Republic,La République française
> ```
> 
> so,do i? #42

This is in reference to the language, not the place, the language is called French, currently the UI displays it as France

**Comment by Sankie005** [comment]
I've opened another branch with the consolidated changes, closing this one to keep it clean.

**Comment by adlai** [comment]
Still occurs; probably delay in deployment?

**Pull request closed without merging**
